name: Build and Test Gems

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
    type: [opened, reopened, edited]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Create Logstash directory
        run: mkdir logstash

      - name: Get latest Logstash versions
        id: version
        run: |
          versions=($(curl -s https://api.github.com/repos/elastic/logstash/releases | jq -r '.[].tag_name' | head -n 3))
          echo "::set-output name=versions::${versions[@]}"

      - name: Test Build Gems on Latest Logstash Release Versions
        run: |
          versions=($(echo "${{ steps.version.outputs.versions }}" | tr ' ' '\n'))

          for major_version in $(printf "%s\n" "${versions[@]}" | cut -d. -f1 | sort -ru); do
            versions_for_major=($(printf "%s\n" "${versions[@]}" | grep "^$major_version\." | sort -rV))

            latest_version="${versions_for_major[0]}"
            previous_version=$(printf "%s\n" "${versions_for_major[@]}" | grep -A 1 "$latest_version" | tail -n 1)

            echo "Building for Logstash versions: $latest_version and $previous_version"

            for version in "$latest_version" "$previous_version"; do
              rm -rf "logstash/$version"

              wget -P "logstash" "https://github.com/elastic/logstash/archive/$version.tar.gz"
              tar -xzf "logstash/$version.tar.gz" --directory "logstash"
              logstash_dir=$(tar -tzf "logstash/$version.tar.gz" | head -n 1 | cut -f1 -d"/")

              echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/$logstash_dir/logstash-core" > gradle.properties
              echo "LOGSTASH_VERSION=$version" >> $GITHUB_ENV

              cd logstash/$logstash_dir
              ./gradlew clean
              ./gradlew assemble
              cd ../..

              ./gradlew clean

              cd ydb_input_plugin
              ../gradlew gem
              cd ..
              cd ydb_output_plugin
              ../gradlew gem
              cd ..
            done
          done
