name: Build and Test Gems

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
    type: [opened, reopened, edited]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Create Logstash directory
        run: mkdir logstash

      - name: Get latest Logstash versions
        id: version
        run: |
          versions=($(curl -s https://api.github.com/repos/elastic/logstash/releases | jq -r '.[].tag_name' | head -n 3))
          echo "::set-output name=versions::${versions[@]}"

      - name: Download and Extract Logstash versions
        run: |
          versions=($(echo "${{ steps.version.outputs.versions }}" | tr ' ' '\n'))
          for version in "${versions[@]}"; do
            wget -P "logstash" "https://github.com/elastic/logstash/archive/$version.tar.gz"
            tar -xzf "logstash/$version.tar.gz" --directory "logstash"

            echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/logstash-$version/logstash-core" > gradle.properties
            echo "LOGSTASH_VERSION=$version" >> $GITHUB_ENV

            cd "logstash/logstash-$version"
            ./gradlew clean
            ./gradlew assemble
            cd ..

            cd ydb_input_plugin
            ../gradlew clean
            ../gradlew gem
            cd ..

            cd ydb_output_plugin
            ../gradlew clean
            ../gradlew gem
            cd ..
          done
