name: Build and Release Gems

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
    type: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Clone Logstash repository
        run: git clone https://github.com/elastic/logstash

      - name: Set LOGSTASH_CORE_PATH
        run: |
          echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/logstash-core" >> $GITHUB_ENV
          echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/logstash-core" > gradle.properties

      - name: Generate logstash-core.jar
        run: |
          cd logstash
          ./gradlew assemble

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Gems in ydb_input_plugin
        run: |
          cd ydb_input_plugin
          ../gradlew gem

      - name: Build Gems in ydb_output_plugin
        run: |
          cd ydb_output_plugin
          ../gradlew gem

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh

      - name: Set up Ruby for Release
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Create GitHub Release
        run: |
          gh release create v${{ github.event.after }} -t "Release v${{ github.event.after }}" -F release_version.txt ydb_input_plugin/*.gem ydb_output_plugin/*.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
