name: Build and Test Gems

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
    type: [opened, reopened, edited]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Get latest Logstash versions
        id: version
        run: |
          versions=($(curl -s https://api.github.com/repos/elastic/logstash/releases | jq -r '.[].tag_name' | head -n 3))
          echo "::set-output name=versions::${versions[@]}"

      - name: Set LOGSTASH_CORE_PATH and Run Tests for all versions
        run: |
          versions=($(echo "${{ steps.version.outputs.versions }}" | tr -d '[:space:]'))
          for version in "${versions[@]}"; do
            wget https://github.com/elastic/logstash/archive/$version.tar.gz
            tar -xzf $version.tar.gz
            echo "LOGSTASH_CORE_PATH=$(pwd)/logstash-$version/logstash-core" > gradle.properties
            echo "LOGSTASH_VERSION=$version" >> $GITHUB_ENV
            cd logstash-$version
            ./gradlew clean
            ./gradlew assemble
            cd ..

            # Add test commands for the specific version
            cd ydb_input_plugin
            ../gradlew clean
            ../gradlew gem
            cd ..

            cd ydb_output_plugin
            ../gradlew clean
            ../gradlew gem
            cd ..
          done
