name: Build and Test Gems

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
    type: [opened, reopened, edited]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Get Logstash versions from releases
        run: |
          versions=$(curl -s https://api.github.com/repos/elastic/logstash/releases | jq -r '.[].tag_name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -Vr | head -n 3)
          echo "LOGSTASH_VERSIONS=$versions" >> $GITHUB_ENV
          echo "Logstash versions: $versions"
      

      - name: Build and Test for each Logstash version
        run: |
          versions=($LOGSTASH_VERSIONS)
          for version in "${versions[@]}"; do
            echo "Current Logstash version: $version"

            wget "https://github.com/elastic/logstash/archive/refs/tags/${version}.tar.gz"
            tar -xzf "${version}.tar.gz"

            cd "logstash-${version}"
            ./gradlew assemble
            cd ..

            echo "LOGSTASH_CORE_PATH=$(pwd)/logstash-${version}/logstash-core" >> $GITHUB_ENV
            echo "LOGSTASH_CORE_PATH=$(pwd)/logstash-${version}/logstash-core" > gradle.properties

            cd "ydb_input_plugin"
            ../gradlew gem
            cd ..

            cd "ydb_output_plugin"
            ../gradlew gem
            cd ..
          done
