name: Build and Test Gems

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
    type: [opened, reopened, edited]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Get Logstash versions
        id: versions
        run: |
          versions=$(curl -s https://api.github.com/repos/elastic/logstash/releases | jq -r '.[].tag_name' | head -n 3)
          echo "::set-output name=versions::${versions}"

      - name: Iterate over Logstash versions
        id: build_steps
        run: |
          versions=(${{ steps.versions.outputs.versions }})
          for version in "${versions[@]}"; do
            echo "::set-output name=version::$version"
            echo "::set-output name=version_underscored::$(echo $version | tr '.' '_')"
          done

      - name: Set LOGSTASH_CORE_PATH and Build Gems
        run: |
          latest_version=$(echo "${{ steps.versions.outputs.versions }}" | head -n 1)
          versions=(${{ steps.build_steps.outputs.version_underscored }})

          for version in "${versions[@]}"; do
            echo "Processing Logstash version: $version"
          
            echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/logstash-core" >> $GITHUB_ENV
            echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/logstash-core" > gradle.properties
            echo "Latest Logstash version: $latest_version"

            # Download Logstash source code for the specified version
            curl -L -o logstash_$version.tar.gz https://github.com/elastic/logstash/archive/$version.tar.gz
            tar -xzf logstash_$version.tar.gz
            mv logstash-$version logstash

            # Generate logstash-core.jar
            cd logstash
            ./gradlew assemble
            cd ..

            # Build Gems in ydb_input_plugin
            cd ydb_input_plugin
            ../gradlew gem
            # Добавьте здесь шаги для тестирования, если необходимо

            # Build Gems in ydb_output_plugin
            cd ../ydb_output_plugin
            ../gradlew gem
            # Добавьте здесь шаги для тестирования, если необходимо

            # Clean up
            rm -rf logstash_$version.tar.gz logstash
          done
        env:
          latest_version: ${{ steps.build_steps.outputs.version }}

      - name: Display Logstash versions and latest version
        run: |
          versions=(${{ steps.versions.outputs.versions }})
          latest_version=${{ steps.build_steps.outputs.version }}
          echo "Logstash versions: ${versions[@]}"
          echo "Latest Logstash version: $latest_version"
