name: Build and Release Gems

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
    type: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      id: LOGSTASH_CORE_PATH
      value: ${{ steps.set_logstash_core.outputs.LOGSTASH_CORE_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Clone Logstash repository
        run: git clone https://github.com/elastic/logstash

      - name: Set LOGSTASH_CORE_PATH
        id: set_logstash_core
        run: |
          echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/logstash-core" >> $GITHUB_ENV
          echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/logstash-core"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Gems in ydb_input_plugin
        run: |
          cd ydb_input_plugin
          ../gradlew gem -PlogstashCorePath=${{ needs.build.outputs.LOGSTASH_CORE_PATH }}

      - name: Build Gems in ydb_output_plugin
        run: |
          cd ydb_output_plugin
          ../gradlew gem -PlogstashCorePath=${{ needs.build.outputs.LOGSTASH_CORE_PATH }}

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Upload release artifacts from ydb_input_plugin
        uses: actions/upload-release-asset@v2
        with:
          file: ydb_input_plugin/*.gem
          asset_name: Gem Files

      - name: Upload release artifacts from ydb_output_plugin
        uses: actions/upload-release-asset@v2
        with:
          file: ydb_output_plugin/*.gem
          asset_name: Gem Files
