name: Build and Test Gems

on:
  push:
    branches:
      - master
      - develop
      - release*
  pull_request:
    type: [opened, reopened, edited]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Check project structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the directory: $(ls -la)"
      

      - name: Create Logstash directory
        run: mkdir logstash

      - name: Get latest Logstash versions
        id: version
        run: |
          versions=($(curl -s https://api.github.com/repos/elastic/logstash/releases | jq -r '.[].tag_name' | head -n 3))
          echo "::set-output name=versions::${versions[@]}"

      - name: Download and Extract Logstash versions
        run: |
          versions=($(echo "${{ steps.version.outputs.versions }}" | tr ' ' '\n'))
          for version in "${versions[@]}"; do
            # Очистка директории перед каждой итерацией
            rm -rf "logstash/$version"

            wget -P "logstash" "https://github.com/elastic/logstash/archive/$version.tar.gz"
            tar -xzf "logstash/$version.tar.gz" --directory "logstash"
            logstash_dir=$(tar -tzf "logstash/$version.tar.gz" | head -n 1 | cut -f1 -d"/")
            logstash_abs_path="$(pwd)/logstash/$logstash_dir"

            # Выводим путь в середине скрипта
            echo "LOGSTASH_ABS_PATH=$logstash_abs_path"

            echo "LOGSTASH_CORE_PATH=$logstash_abs_path/logstash-core" > gradle.properties
            echo "LOGSTASH_VERSION=$version" >> $GITHUB_ENV

              # Вывод текущей директории
            echo "Current directory: $(pwd)"
          
            ./gradlew clean
            ./gradlew assemble

            # После выполнения команд выводим текущую директорию снова
            echo "Current directory after gradlew: $(pwd)"
            cd ..

            # Используйте абсолютные пути к плагинам
            cd "$(pwd)/ydb-logstash-plugins-add-modules/ydb_input_plugin"
            ../../gradlew clean
            ../../gradlew gem
            cd ..

            cd "$(pwd)/ydb-logstash-plugins-add-modules/ydb_output_plugin"
            ../../gradlew clean
            ../../gradlew gem
            cd ..
          done
      
      
      
