name: Publish Gems

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Create Logstash directory
        run: mkdir logstash

      - name: Get latest Logstash versions
        id: version
        run: |
          versions=($(curl -s https://api.github.com/repos/elastic/logstash/releases | jq -r '.[].tag_name'))
          echo "::set-output name=versions::${versions[@]}"

      - name: Create or Update GitHub Release
        run: |
          versions=($(echo "${{ steps.version.outputs.versions }}" | tr ' ' '\n'))

          for current_version in "${versions[@]}"; do
              rm -rf "logstash/$current_version"
          
              wget -P "logstash" "https://github.com/elastic/logstash/archive/$current_version.tar.gz"
              tar -xzf "logstash/$current_version.tar.gz" --directory "logstash"
              logstash_dir=$(tar -tzf "logstash/$current_version.tar.gz" | head -n 1 | cut -f1 -d"/")
          
              echo "LOGSTASH_CORE_PATH=$(pwd)/logstash/$logstash_dir/logstash-core" > gradle.properties
              echo "LOGSTASH_VERSION=$current_version" >> $GITHUB_ENV
          
              cd logstash/$logstash_dir
              ./gradlew clean
              ./gradlew assemble
          
              cd ../..
          
              ./gradlew clean
          
              ./gradlew gem
          
              # Получение тега, который мы запушили
              tag=$(git describe --tags --abbrev=0)
          
              # Создание или обновление релиза
              if gh release view "$tag" &> /dev/null; then
                # Релиз существует, выполнить upload

                for gem_file in $(find . -name '*.gem'); do
                  # Переименование gem файлов с добавлением версии Logstash
                  mv "$gem_file" "${gem_file%.*}_${current_version}.gem"
                done

                gh release upload "$tag" *.gem --clobber
              else
                # Релиз не существует, выполнить create

                for gem_file in $(find . -name '*.gem'); do
                  # Переименование gem файлов с добавлением версии Logstash
                  mv "$gem_file" "${gem_file%.*}_${current_version}.gem"
                done

                gh release create "$tag" -t "Release $tag" \
                  -n "Built with Logstash Stable Versions" \
                  *.gem
              fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
