name: Publish Gems

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Get latest Logstash versions
        id: version
        run: |
          versions=($(curl -s https://api.github.com/repos/elastic/logstash/releases | jq -r '.[].tag_name'))
          echo "::set-output name=versions::${versions[@]}"

      - name: Create or Update GitHub Release
        run: |
          versions=($(echo "${{ steps.version.outputs.versions }}" | tr ' ' '\n'))

          for current_version in "${versions[@]}"; do
              tag=$(git describe --tags --abbrev=0)

              if gh release view "$tag" &> /dev/null; then
                find . -type f -name '*.gem' -not -path '*/vendor/*' -not -path '*/logstash/*' | while read -r gem_file; do
                  mv "$gem_file" "$(basename -- "$gem_file" .gem)_${current_version}.gem"
                done

                gh release upload "$tag" */*.gem --clobber
              else
                find . -type f -name '*.gem' -not -path '*/vendor/*' -not -path '*/logstash/*' | while read -r gem_file; do
                  mv "$gem_file" "$(basename -- "$gem_file" .gem)_${current_version}.gem"
                done

                gh release create "$tag" -t "Release $tag" \
                  -n "Built with Logstash Stable Versions" \
                  */*.gem
              fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
